steps:
  # 1️⃣ Instalar Node y dependencias
  - name: 'node:22.17-bullseye'
    id: 'Install dependencies'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Installing dependencies..."
        npm ci

  # 2️⃣ Detectar apps afectadas
  - name: 'node:22.17-bullseye'
    id: 'Detect affected apps'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Detecting affected projects with Nx..."
        npx nx print-affected --target=build --base=origin/main~1 --head=HEAD --select=projects > /workspace/affected_apps.txt
        echo "Affected apps saved to /workspace/affected_apps.txt"

  # 3️⃣ Construir y pushear Docker images de apps afectadas
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build and push Docker images'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ ! -f /workspace/affected_apps.txt ]; then
          echo "No affected apps detected. Exiting."
          exit 0
        fi
        AFFECTED_APPS=$(cat /workspace/affected_apps.txt)
        if [ -z "$AFFECTED_APPS" ]; then
          echo "No affected apps detected. Exiting."
          exit 0
        fi
        for app in $AFFECTED_APPS; do
          IMAGE="gcr.io/${PROJECT_ID}/${app}"
          echo "🚀 Building Docker image for $app..."
          docker build -t "$IMAGE" "./apps/$app"
          echo "📤 Pushing Docker image for $app..."
          docker push "$IMAGE"
        done

  # 4️⃣ Desplegar apps a Cloud Run usando gcloud
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy to Cloud Run'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        AFFECTED_APPS=$(cat /workspace/affected_apps.txt)
        if [ -z "$AFFECTED_APPS" ]; then
          echo "No apps to deploy. Exiting."
          exit 0
        fi
        for app in $AFFECTED_APPS; do
          IMAGE="gcr.io/${PROJECT_ID}/${app}"
          echo "🚀 Deploying $app to Cloud Run..."
          gcloud run deploy "$app" \
            --image="$IMAGE" \
            --platform=managed \
            --region=us-central1 \
            --quiet

# 5️⃣ Opciones generales de la build
options:
  logging: CLOUD_LOGGING_ONLY  # Evita errores con service accounts

# 6️⃣ Timeout opcional
timeout: "1800s"  # 30 minutos
