steps:
  # 1️⃣ Instalar Node y dependencias
  - name: 'node:22.17-bullseye'
    id: 'Install dependencies'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Installing dependencies..."
        npm ci

  # 2️⃣ Detectar apps afectadas
  - name: 'node:22.17-bullseye'
    id: 'Affected apps'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Detecting affected projects..."
        # Detectar apps afectadas usando Nx
        npx nx print-affected --target=build --base=origin/main~1 --head=HEAD --select=projects > /workspace/affected_apps.txt
        echo "Detected apps saved to /workspace/affected_apps.txt"

  # 3️⃣ Construir y desplegar solo apps afectadas
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build and deploy apps'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [ ! -f /workspace/affected_apps.txt ]; then
          echo "No affected apps file found."
          exit 0
        fi
        AFFECTED_APPS=$(cat /workspace/affected_apps.txt)
        if [ -z "$AFFECTED_APPS" ]; then
          echo "No apps affected. Nothing to build."
          exit 0
        fi
        echo "Affected apps: $AFFECTED_APPS"
        for app in $AFFECTED_APPS; do
          echo "🚀 Building $app..."
          docker build -t gcr.io/$PROJECT_ID/$app ./apps/$app
          docker push gcr.io/$PROJECT_ID/$app
          echo "Deploying $app to Cloud Run..."
          gcloud run deploy $app \
            --image=gcr.io/$PROJECT_ID/$app \
            --platform=managed \
            --region=us-central1 \
            --quiet

# 4️⃣ Opciones generales de la build
options:
  logging: CLOUD_LOGGING_ONLY

# 5️⃣ Timeout opcional
timeout: "1800s"
